services:
  vaultwarden:
    image: vaultwarden/server:latest
    container_name: vaultwarden
    restart: on-failure
    ports:
      - "8081:80"
    volumes:
      - /mnt/vault/vaultwarden:/data
    environment:
      DOMAIN: ${DOMAIN}
      ADMIN_TOKEN: ${ADMIN_TOKEN}
      SIGNUPS_ALLOWED: ${SIGNUPS_ALLOWED}
      INVITATIONS_ALLOWED: ${INVITATIONS_ALLOWED}
      WEBSOCKET_ENABLED: ${WEBSOCKET_ENABLED}
      LOG_FILE: ${LOG_FILE}
    healthcheck:
      test: ["CMD", "wget", "-f", "http://localhost:80/alive"]
      interval: 30s
      timeout: 10s
      retries: 3
